title: Liangshun ZHANG's Homepage
page-top-title: Liangshun ZHANG's Group &ensp;@&ensp;ECUST
top-section-bg-text: Polymer Theory and Simulations
home-subtitle: Liangshun ZHANG&ensp;|&ensp;张良顺
copyright-text: '&copy; zhangls 2023-2026. All Rights Reserved.'
